# Generated by Django 2.1.7 on 2019-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerwikiplayer',
            name='birth_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
