# Generated by Django 2.1.7 on 2019-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='f_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='f_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='s_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='s_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='x1_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='x1_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='x2_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='x2_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='p_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='p_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamepick',
            name='version',
            field=models.IntegerField(default=0),
        ),

        # triggers to increase game version when pick is updated
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION pass_score_from_pick()
  RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'UPDATE')
  THEN
    IF OLD.score != NEW.score THEN 
      update games g 
         set g.score = g.score + NEW.score,
             g.version = g.version + 1
       where g.id = NEW.game_id;
    END IF; 

    RETURN NEW;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION pass_score_from_pick();"""
        ),
        migrations.RunSQL(
            """
CREATE TRIGGER trg_pass_score_from_pick
AFTER UPDATE ON game_picks
FOR EACH ROW EXECUTE PROCEDURE pass_score_from_pick();
            """,
            """DROP TRIGGER trg_pass_score_from_pick ON game_picks;"""
        ),
    ]
