# Generated by Django 2.1.7 on 2019-03-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190311_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEventSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('simulated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'match_event_simulations',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='simulation_from_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='import_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matcheventsimulation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match'),
        ),
        migrations.AddField(
            model_name='matcheventsimulation',
            name='match_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.MatchEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='matcheventsimulation',
            unique_together={('match', 'match_event')},
        ),
    ]
