# Generated by Django 2.1.7 on 2019-03-13 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190312_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('d', 'Defender'), ('m', 'Midfielder'), ('f', 'Forward'), ('g', 'Goalkeeper'), ('s', 'Substitute'), ('u', 'Unknown')], max_length=1, null=True)),
                ('jersey_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'match_players',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='has_lineups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.CharField(choices=[('p', 'Pregame'), ('f', 'First half'), ('h', 'Half time'), ('s', 'Second half'), ('bx1', 'Break x1'), ('x1', 'First ext'), ('bx2', 'Break x2'), ('x2', 'Second ext'), ('bp', 'Break penalties'), ('pe', 'Penalties'), ('pg', 'Post game')], default='p', max_length=3),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('u', 'Unknown'), ('w', 'Waiting'), ('l', 'Lineups'), ('g', 'Game'), ('e', 'Ended'), ('c', 'Cancelled')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='seasonteamplayer',
            name='position',
            field=models.CharField(choices=[('d', 'Defender'), ('m', 'Midfielder'), ('f', 'Forward'), ('g', 'Goalkeeper'), ('s', 'Substitute'), ('u', 'Unknown')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='position',
            field=models.CharField(choices=[('d', 'Defender'), ('m', 'Midfielder'), ('f', 'Forward'), ('g', 'Goalkeeper'), ('s', 'Substitute'), ('u', 'Unknown')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Player'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Team'),
        ),
    ]
