# Generated by Django 2.1.7 on 2019-03-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190313_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='optafeed',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match'),
        ),
    ]
