# Generated by Django 2.1.7 on 2019-03-13 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_optafeed_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('minute', models.IntegerField()),
                ('second', models.IntegerField()),
                ('type', models.IntegerField()),
                ('score', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Game')),
                ('game_pick', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.GamePick')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Team')),
            ],
            options={
                'db_table': 'game_events',
            },
        ),
        # triggers to increase game version when pick is updated
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION pass_score_from_game_event()
  RETURNS TRIGGER AS $$
BEGIN 
    update game_picks
       set score = score + NEW.score,
           version = version + 1
     where id = NEW.game_pick_id;
     
    update games
       set score = score + NEW.score,
           version = version + 1
     where id = NEW.game_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION pass_score_from_game_event();"""
        ),
        migrations.RunSQL(
            """
CREATE TRIGGER trg_pass_score_from_game_event
AFTER INSERT ON game_events
FOR EACH ROW EXECUTE PROCEDURE pass_score_from_game_event();
            """,
            """DROP TRIGGER trg_pass_score_from_game_event ON game_events;"""
        ),
        migrations.RunSQL(
            """DROP TRIGGER if exists trg_pass_score_from_pick ON game_picks;""",
            """"""
        ),
        migrations.RunSQL(
            """DROP FUNCTION if exists pass_score_from_pick();""",
            """"""
        ),
    ]
