# Generated by Django 2.1.7 on 2019-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gameevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matcheventprocessor',
            name='type',
            field=models.IntegerField(choices=[(1, 'points'), (2, 'system')]),
        ),
    ]
