# Generated by Django 2.1.7 on 2019-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190314_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='is_star',
            field=models.BooleanField(default=False),
        ),
    ]
