# Generated by Django 2.1.7 on 2019-03-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teamplayer_is_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('ordering', models.IntegerField()),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('duration', models.IntegerField(help_text='duration in minutes')),
                ('multiplier', models.FloatField()),
            ],
            options={
                'db_table': 'powerups',
            },
        ),
        migrations.CreateModel(
            name='PowerUpAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Action')),
                ('power_up', models.ForeignKey(db_column='powerup_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.PowerUp')),
            ],
            options={
                'db_table': 'powerup_actions',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Region'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.TextField(blank=True),
        ),
    ]
