# Generated by Django 2.1.7 on 2019-03-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190320_1905'),
    ]

    operations = [

        # insert actions
        migrations.RunSQL(
            '''INSERT INTO actions(id,description,name,score,ordering) values
(70, 'Last Line Save', 'Save off line', 10, 100),
(71, 'Last Man Tackle', 'Last Man Tackle', 10, 200),
(36, 'Defensive Block', 'Defensive Block', 8, 300),
(32, 'Tackle - Won', 'Tackle + Ball', 6, 400),
(31, 'Interception', 'Intercepts Ball', 5, 500),
(33, 'Tackle - Won (without Possession)', 'Tackle', 5, 600),
(38, 'Effective Clearance', 'Clears Ball', 3, 700),
(18, 'Aerial Duel - Won', 'Header Won', 2, 800),
(19, 'Aerial Duel - Lost', 'Header Lost', -2, 900),
(26, 'Foul - Conceded', 'Foul Conceded', -2, 1000),
(57, 'Penalty Conceded', 'Penalty Fault', -12, 1100),
(49, 'Own Goal', 'Own Goal', -15, 1200),
(27, 'Handball Conceded', 'Handball', -3, 1300),
(58, 'Yellow Card', 'Yellow Card', -8, 1400),
(59, '2nd Yellow Card', '2nd Yellow Card', -8, 1500),
(60, 'Red Card', 'Red Card', -18, 1600),
(69, 'Won Corner', 'Won Corner', 4, 1700),
(73, 'Penalty Won', 'Pen Won', 20, 1800),
(61, 'Great Skill', 'Great Skill', 8, 1900),
(55, 'Successful Take On (dribble)', 'Dribble Success', 6, 2000),
(25, 'Foul - Won', 'Foul Won', 2, 2100),
(67, 'Dispossessed', 'Loses Ball', -2, 2200),
(56, 'Unsuccessful dribble', 'Dribble Fail', -2, 2300),
(62, 'Big Error - lead to shot', 'Bad Mistake', -8, 2400),
(80, 'Goalkeeper Save', 'Save', 12, 2500),
(37, 'Goalkeeper Claim', 'Cross Caught', 6, 2600),
(75, 'Goalkeeper Punch', 'Punch Clear', 5, 2700),
(77, 'Keeper pick-up', 'Pick-up', 2, 2800),
(87, 'Goal Kick  Successful', 'Goal Kick', 2, 2900),
(85, 'Goalkeeper Throw - Successful', 'Keeper Throw', 2, 3000),
(88, 'Goal Kick Unsuccessful', 'Goal Kick Miss', -1, 3100),
(79, 'Cross not claimed', 'Cross Dropped', -4, 3200),
(7, 'Assist', 'Assist', 25, 3300),
(8, 'Key Pass', 'Key Pass', 5, 3400),
(68, 'Through Ball', 'Through Ball', 5, 3500),
(5, 'Successful Cross - Bonus', 'Crosses Ball', 5, 3600),
(29, 'Corners Into box - Successful', 'Corner Success', 4, 3700),
(2, 'Pass - Successful', 'Pass', 1, 3800),
(3, 'Pass - Unsuccessful', 'Pass Miss', -2, 3900),
(6, 'Unsuccessful Crosses Total (excl corners & freekicks)', 'Cross Miss', -2, 4000),
(86, 'Goalkeeper Throw - Unsuccessful', 'Throw Miss', -2, 4100),
(64, 'Big Error - lead to goal', 'Big Mistake', -12, 4200),
(45, 'Goal', 'GOAL!!', 50, 4300),
(63, 'Shot hit the Post', 'Shot Hit Post', 16, 4400),
(43, 'Shot on Target', 'Shot On Goal', 12, 4500),
(53, 'Shot Blocked', 'Shot Blocked', 8, 4600),
(44, 'Shot off Target', 'Shot Off Goal', 5, 4700),
(65, 'Caught Offside', 'Offside', -3, 4800),
(72, 'Big Chance Missed', 'Big Miss!', -12, 4900),
(74, 'Penalty Missed', 'Pen Miss', -14, 5000);''',
            '''DELETE FROM actions;'''),

        # insert powerups
        migrations.RunSQL(
            '''INSERT INTO powerups(id,name,duration,multiplier) values
(1, 'Golden Gloves', 600, 2),
(2, 'Defensive Rock', 600, 2),
(3, 'Anchorman', 600, 2),
(4, 'Playmaker', 600, 2),
(5, 'Sharp Shooter', 600, 2),
(6, 'Wing Wizard', 600, 2);''',
            '''DELETE FROM powerups;'''),

        # insert powerup actions
        migrations.RunSQL(
            '''INSERT INTO powerup_actions(powerup_id, action_id, ordering) values
(1, 80, 10),
(1, 37, 20),
(1, 75, 30),
(1, 2, 40),
(1, 88, 50),
(1, 3, 60),
(1, 58, 70),


(2, 70, 10),
(2, 36, 20),
(2, 32, 30),
(2, 31, 40),
(2, 33, 50),
(2, 38, 60),
(2, 18, 70),
(2, 19, 80),
(2, 64, 90),
(2, 62, 100),
(2, 26, 110),
(2, 57, 120),
(2, 49, 130),
(2, 58, 140),

(3, 2, 10),
(3, 32, 20),
(3, 38, 30),
(3, 33, 40),
(3, 18, 50),
(3, 19, 60),
(3, 3, 70),
(3, 26, 80),
(3, 64, 90),
(3, 62, 100),
(3, 58, 110),

(4, 45, 10),
(4, 2, 20),
(4, 8, 30),
(4, 68, 40),
(4, 5, 50),
(4, 29, 60),
(4, 7, 70),
(4, 3, 80),
(4, 6, 90),
(4, 65, 100),
(4, 58, 110),

(5, 45, 10),
(5, 63, 20),
(5, 43, 30),
(5, 53, 40),
(5, 44, 50),
(5, 67, 60),
(5, 65, 70),
(5, 72, 80),
(5, 74, 90),
(5, 58, 100),
(5, 27, 110),

(6, 45, 10),
(6, 69, 20),
(6, 73, 30),
(6, 55, 40),
(6, 25, 50),
(6, 7, 60),
(6, 8, 70),
(6, 67, 80),
(6, 56, 90),
(6, 72, 100),
(6, 74, 110);''',
            '''DELETE FROM powerup_actions;'''
        ),
    ]
