# Generated by Django 2.1.7 on 2019-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_actions_powerup_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='powerup',
            name='icon_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='powerup',
            name='duration',
            field=models.IntegerField(help_text='duration in seconds'),
        ),
    ]
