# Generated by Django 2.1.7 on 2019-03-20 20:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190320_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePowerUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('position', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('multiplier', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Game')),
                ('powerup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.PowerUp')),
            ],
            options={
                'db_table': 'game_powerups',
            },
        ),
        migrations.RenameField(
            model_name='powerupaction',
            old_name='power_up',
            new_name='powerup',
        ),
        migrations.AlterField(
            model_name='powerupaction',
            name='powerup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.PowerUp'),
        ),
    ]
