# Generated by Django 2.1.7 on 2019-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190320_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_score',
            field=models.FloatField(null=True),
        ),
    ]
