# Generated by Django 2.1.7 on 2019-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_matchleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
