# Generated by Django 2.1.7 on 2019-03-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190326_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Free'), (2, 'Cash'), (3, 'Cash Plus')], db_index=True, default=0),
        ),
        migrations.RunSQL(
            '''
insert into match_rewards(match_id, position, amount)
select * 
  from (
select id, 1, 100 from matches
union all
select id, 2, 50 from matches
union all
select id, 3, 25 from matches
union all
select id, 4, 15 from matches
union all
select id, 5, 10 from matches
) t
            ''',
            '''delete from match_rewards'''
        )
    ]
