# Generated by Django 2.1.7 on 2019-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190326_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='is_star',
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='is_star',
            field=models.BooleanField(default=False),
        ),
    ]
