# Generated by Django 2.1.7 on 2019-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190328_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='from_lineups',
            field=models.BooleanField(default=False),
        ),
    ]
