# Generated by Django 2.1.7 on 2019-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_matchplayer_from_lineups'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
