# Generated by Django 2.1.7 on 2019-03-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190330_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('type', models.CharField(max_length=15)),
                ('screen_type', models.IntegerField(choices=[(1, 'lobby'), (2, 'gameplay'), (3, 'fulltime')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match')),
            ],
            options={
                'db_table': 'match_headlines',
            },
        ),
    ]
