# Generated by Django 2.1.7 on 2019-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190330_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='crest_url',
            field=models.TextField(blank=True),
        ),
    ]
