# Generated by Django 2.1.7 on 2019-04-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190403_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL('''
update teams
   set short_name = null
 where short_name = ''
        ''', ''''''),
        migrations.RunSQL('''
update teams
   set crest_url = null
 where crest_url = ''
            ''', ''''''),
    ]
