# Generated by Django 2.1.7 on 2019-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190404_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
