# Generated by Django 2.1.7 on 2019-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_player_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
