# Generated by Django 2.1.7 on 2019-04-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190405_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rewarded',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
