# Generated by Django 2.1.7 on 2019-04-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190419_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Cancelled'), (3, 'Ignored')], default=1),
        ),
    ]
