# Generated by Django 2.1.7 on 2019-04-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_matchevent_status'),
    ]

    operations = [
        migrations.RunSQL(
            '''create index idx_opta_feed_unprocessed on opta_feeds(id) where status = 1;''',
            '''drop index idx_opta_feed_unprocessed;'''
        ),
        migrations.RunSQL(
            """
create or replace function update_match_leaderboard(p_match_id uuid)
  returns void as $$
begin
  update match_leaderboard
     set score = t.score,
         position = t.position
    from (select g.id game_id,
                 g.score,
                 rank() over(order by g.score desc) as position
            from games g
           where g.match_id = p_match_id
         ) t
   where match_leaderboard.game_id = t.game_id
     and match_leaderboard.match_id = p_match_id;
end;
$$ language plpgsql;
            """,
            """
create or replace function update_match_leaderboard(p_match_id uuid)
  returns void as $$
begin
  update match_leaderboard
     set score = t.score,
         position = t.position
    from (select g.id game_id,
                 g.score,
                 rank() over(order by g.score desc) as position
            from games g
           where g.match_id = p_match_id
         ) t
   where match_leaderboard.game_id = t.game_id;
end;
$$ language plpgsql;"""
        ),
    ]
