# Generated by Django 2.1.7 on 2019-04-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190420_0933'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='matchplayer',
            index_together={('match', 'player', 'team')},
        ),
    ]
