# Generated by Django 2.1.7 on 2019-04-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190420_0946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='withdrawrequest',
            table='withdraw_requests',
        ),
    ]
