# Generated by Django 2.1.7 on 2019-04-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190423_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
