# Generated by Django 2.1.7 on 2019-04-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190423_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
