# Generated by Django 2.1.7 on 2019-04-23 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0039_team_abbr'),
    ]

    operations = [
        migrations.RunSQL(
            '''create sequence if not exists user_guest_index;''',
            '''drop sequence if exists user_guest_index;''',
        )
    ]
