# Generated by Django 2.1.7 on 2019-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_matchplayer_played_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchheadline',
            name='image_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
