# Generated by Django 2.1.7 on 2019-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_matchheadline_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepick',
            name='user_swapped',
            field=models.BooleanField(default=True),
        ),
    ]
