# Generated by Django 2.1.7 on 2019-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_matchnotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='avg_score',
            field=models.FloatField(null=True),
        ),
        migrations.RunSQL(
            '''update match_players mp
                  set avg_score=(select p.avg_score from players p where p.id = mp.player_id);''',
            '''''',
        )
    ]
