# Generated by Django 2.1.7 on 2019-06-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_powerups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser'),
        ),
        migrations.AddField(
            model_name='gamepowerup',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
    ]
