# Generated by Django 2.1.7 on 2019-06-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20190620_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bonus_powerups',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser'),
        ),
    ]
