# Generated by Django 2.1.7 on 2020-05-24 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20190627_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_id', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'competition_editions',
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_id', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('competition_edition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CompetitionEdition')),
            ],
            options={
                'db_table': 'competition_phases',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('', 'Empty'), ('u', 'Unknown'), ('w', 'Waiting'), ('l', 'Lineups'), ('g', 'Game'), ('e', 'Ended'), ('c', 'Cancelled')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='competitionedition',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Competition'),
        ),
    ]
