# Generated by Django 2.1.7 on 2020-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20200524_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ortec_selection_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
