# Generated by Django 2.1.7 on 2020-06-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_team_ortec_selection_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optafeeditem',
            unique_together={('match', 'unique_id', 'event_id')},
        ),
    ]
