# Generated by Django 2.1.7 on 2020-06-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200610_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
