# Generated by Django 2.1.7 on 2020-10-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_match_last_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchheadline',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
