# Generated by Django 2.1.7 on 2020-11-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20201025_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('match', 'player', 'team')},
        ),
        migrations.AlterIndexTogether(
            name='matchplayer',
            index_together=set(),
        ),
    ]
