# Generated by Django 2.1.7 on 2020-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20201128_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optafeeditemversion',
            name='version',
            field=models.CharField(max_length=64),
        ),
    ]
