# Generated by Django 2.1.7 on 2020-12-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20201129_1959'),
    ]

    operations = [
        # insert powerups
        migrations.RunSQL(
            '''INSERT INTO powerups(id,name,duration,multiplier) values
(7, 'Double Points', 600, 2);''',
            '''DELETE FROM powerups;'''),

        # insert powerup actions
        migrations.RunSQL(
            '''INSERT INTO powerup_actions(powerup_id, action_id, ordering)
(select 7,
        id,
        (row_number() over(order by id))*10
   from actions
);''',
            '''DELETE FROM powerup_actions;'''
        ),
    ]
