# Generated by Django 2.1.7 on 2020-12-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20201204_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.TextField(null=True),
        ),
    ]
