# Generated by Django 2.1.7 on 2020-12-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_player_nick_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together=set(),
        ),
    ]
