# Generated by Django 2.1.7 on 2020-12-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_wiki', '0002_auto_20190404_1225'),
        ('core', '0062_auto_20201218_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='soccer_wiki_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soccer_wiki.SoccerWikiPlayer'),
        ),
    ]
