# Generated by Django 2.1.7 on 2020-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20201218_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
