# Generated by Django 2.1.7 on 2020-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_matchevent_period'),
    ]

    operations = [
        # triggers to increase game version when pick is updated
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION decrease_score_on_game_event_deletion()
  RETURNS TRIGGER AS $$
BEGIN 
    update game_picks
       set score = score - OLD.score,
           version = version + 1
     where id = OLD.game_pick_id;

    update games
       set score = score - OLD.score,
           version = version + 1
     where id = OLD.game_id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION decrease_score_on_game_event_deletion();"""
        ),
        migrations.RunSQL(
            """
CREATE TRIGGER trg_decrease_score_on_game_event_deletion
AFTER DELETE ON game_events
FOR EACH ROW EXECUTE PROCEDURE decrease_score_on_game_event_deletion();
            """,
            """DROP TRIGGER trg_decrease_score_on_game_event_deletion ON game_events;"""
        ),
    ]
