# Generated by Django 2.1.7 on 2021-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20201226_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepick',
            name='ended_minute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamepick',
            name='ended_second',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION set_ended_minute_and_second()
  RETURNS TRIGGER AS $$
BEGIN 
    if OLD.ended_at is null and NEW.ended_at is not null then
      select matches.minute,
             matches.second
        into new.ended_minute,
             new.ended_second
        from matches,
             games
       where games.id = NEW.game_id
         and games.match_id = matches.id;
    end if;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION set_ended_minute_and_second();"""
        ),
        migrations.RunSQL(
            """
CREATE TRIGGER trg_set_ended_minute_and_second
BEFORE UPDATE ON game_picks
FOR EACH ROW EXECUTE PROCEDURE set_ended_minute_and_second();
            """,
            """DROP TRIGGER trg_set_ended_minute_and_second ON game_picks;"""
        ),
    ]
