# Generated by Django 2.2 on 2021-01-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20210130_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("""
        update users
           set name_changed = true
         where users.name not like 'Guest#%'
           """, """""")
    ]
