# Generated by Django 2.2 on 2021-02-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_customuser_name_changed'),
    ]

    operations = [
        migrations.RunSQL('''create extension if not exists pg_trgm;''', ''''''),
        migrations.RunSQL('''
        CREATE INDEX idx_users_name ON users USING gist (name gist_trgm_ops);
        '''),
    ]
