# Generated by Django 2.2 on 2021-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20210221_1246'),
    ]

    operations = [
        migrations.RunSQL(
            """
update users
   set name = t.name
from (select id,
             name || num as name
      from (select id,
                   name,
                   row_number() over (partition by name order by created_at) num
            from users
            order by name, num) t
      where num > 1
     ) t
where users.id = t.id""",
            """"""
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
