# Generated by Django 2.2 on 2021-03-24 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20210322_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, help_text='Empty end time means permanent ban', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='penalties', to='core.CustomUser')),
            ],
            options={
                'db_table': 'ban_penalties',
            },
        ),
    ]
