# Generated by Django 2.2 on 2021-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_banpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
