# Generated by Django 2.2 on 2021-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20210428_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='has_real_timestamp',
            field=models.BooleanField(default=False),
        ),
    ]
