# Generated by Django 2.2 on 2021-05-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_subscription_subscriptionhistory_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='app_user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='core.Subscription'),
        ),
    ]
