# Generated by Django 2.2 on 2021-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_subscriptionrequest_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
