# Generated by Django 2.2 on 2021-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_game_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('match', 'user'), ('user', 'num')},
        ),
        migrations.RunSQL(
            '''
update games
   set num = t.num
  from (
select g.id,
       row_number() over(partition by g.user_id order by g.created_at) num
  from games g
  ) t
 where games.id = t.id
    ''',
            ''''''
        )
    ]
