# Generated by Django 2.2 on 2021-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210602_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='influencer',
            field=models.BooleanField(default=False),
        ),
    ]
