# Generated by Django 2.2 on 2021-06-17 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_customuser_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.IntegerField(choices=[(1, 'Premium'), (2, 'Lite')])),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser')),
            ],
            options={
                'db_table': 'manual_subscriptions',
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='manual_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='core.ManualSubscription'),
        ),
    ]
