# Generated by Django 2.2 on 2021-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20210617_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_tier',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Premium'), (2, 'Lite')], default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Premium'), (2, 'Lite')], null=True),
        ),
        migrations.AlterField(
            model_name='manualsubscription',
            name='tier',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Premium'), (2, 'Lite')]),
        ),
        migrations.RunSQL(
            '''update users set subscription_tier = 1 where premium = true;''',
            ''''''
        ),
        migrations.RunSQL(
            '''update subscriptions set tier = 1;''',
            ''''''
        )
    ]
