# Generated by Django 2.2 on 2021-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_game_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_rank_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
