# Generated by Django 2.2 on 2021-09-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20210920_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectionteamplayer',
            unique_together={('selection_id', 'player')},
        ),
        migrations.AlterIndexTogether(
            name='selectionteamplayer',
            index_together={('selection_id', 'player')},
        ),
        migrations.RemoveField(
            model_name='selectionteamplayer',
            name='team',
        ),
    ]
