# Generated by Django 2.2 on 2024-02-03 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20210920_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPackType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'card_pack_types',
            },
        ),
        migrations.CreateModel(
            name='PlayersTeams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'players_teams',
            },
        ),
        migrations.CreateModel(
            name='PlayerBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
            options={
                'db_table': 'player_bucket',
            },
        ),
        migrations.CreateModel(
            name='AssignedPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayerBucket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomUser')),
            ],
            options={
                'db_table': 'assigned_players',
            },
        ),
        migrations.CreateModel(
            name='AssignedCardPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(default=False)),
                ('card_pack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CardPackType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomUser')),
            ],
            options={
                'db_table': 'assigned_card_packs',
            },
        ),
    ]
