# Generated by Django 2.2 on 2024-02-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbucket',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayersTeams'),
        ),
    ]
