# Generated by Django 2.2 on 2024-02-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcardpack',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='common_guarantee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='legendary_guarantee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='rare_guarantee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='ultra_rare_guarantee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='uncommon_guarantee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
        migrations.AlterField(
            model_name='playersteams',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
    ]
