# Generated by Django 2.2 on 2024-02-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaderboard_types',
            },
        ),
        migrations.AddField(
            model_name='matchleaderboard',
            name='leaderboard_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.LeaderboardType'),
        ),
    ]
