# Generated by Django 2.2 on 2024-02-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboards', to='core.Country'),
        ),
    ]
