# Generated by Django 2.2 on 2024-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(choices=[('season', 'Season'), ('country', 'Country'), ('team', 'Team'), ('matchday', 'Matchday')], max_length=50),
        ),
    ]
