# Generated by Django 2.2 on 2024-02-08 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_update_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbucket',
            name='rarity',
        ),
        migrations.AddField(
            model_name='assignedplayer',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('ultra_rare', 'Ultra Rare'), ('legendary', 'Legendary')], default='common', max_length=10),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='bronze',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='common',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='diamond',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='game_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='gold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='legendary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='platinum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='rare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='real_popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='silver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='ultra_rare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='uncommon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerbucket',
            name='usable_popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbucket',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.DeleteModel(
            name='PlayersTeams',
        ),
    ]
