# Generated by Django 2.2 on 2024-02-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_update_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpacktype',
            old_name='common_guarantee',
            new_name='tier1_guaranteed',
        ),
        migrations.RenameField(
            model_name='cardpacktype',
            old_name='legendary_guarantee',
            new_name='tier2_guaranteed',
        ),
        migrations.RenameField(
            model_name='cardpacktype',
            old_name='rare_guarantee',
            new_name='tier3_guaranteed',
        ),
        migrations.RenameField(
            model_name='cardpacktype',
            old_name='ultra_rare_guarantee',
            new_name='tier4_guaranteed',
        ),
        migrations.RenameField(
            model_name='cardpacktype',
            old_name='uncommon_guarantee',
            new_name='tier5_guaranteed',
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardpacktype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
