# Generated by Django 2.2 on 2024-02-09 15:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('purchase_img_url', models.TextField(blank=True, null=True)),
                ('contract_abbr', models.TextField()),
                ('contract_address', models.TextField()),
                ('token_id', models.TextField(blank=True, null=True)),
                ('stripe_price_id', models.TextField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('default_quantity', models.IntegerField(blank=True, null=True)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('whitelist_required', models.BooleanField(default=False)),
                ('start_date_at', models.DateTimeField()),
                ('close_date_at', models.DateTimeField()),
                ('bonus_quantity', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.IntegerField(choices=[(1, 'CreditToken'), (2, 'CardPack')], default=1)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('contract', models.TextField()),
                ('token_id', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_uuid', models.TextField(blank=True, null=True)),
                ('payment_platform_uuid', models.TextField(blank=True, null=True)),
                ('blockchain_order_status', models.IntegerField(choices=[(0, 'Mint not started'), (1, 'Mint in progress'), (2, 'Mint Failed'), (3, 'Mint Succeeded'), (4, 'Mint Timeout')], default=0)),
                ('payment_platform_status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Failed'), (2, 'Completed'), (3, 'Expired')], default=0)),
                ('payment_platform_type', models.IntegerField(choices=[(1, 'Stripe')], default=1)),
                ('cancel_url', models.TextField(blank=True, null=True)),
                ('success_url', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser')),
            ],
            options={
                'db_table': 'purchase_trackers',
            },
        ),
    ]
