# Generated by Django 2.2 on 2024-02-22 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('contract', models.TextField(blank=True, null=True)),
                ('token_id', models.TextField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_uuid', models.TextField(blank=True, null=True)),
                ('payment_platform_uuid', models.TextField(blank=True, null=True)),
                ('blockchain_order_status', models.IntegerField(choices=[(0, 'Mint not started'), (1, 'Mint in progress'), (2, 'Mint Failed'), (3, 'Mint Succeeded'), (4, 'Mint Timeout')], default=0)),
                ('payment_platform_status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Failed'), (2, 'Completed'), (3, 'Expired')], default=0)),
                ('payment_platform_type', models.IntegerField(choices=[(1, 'Stripe'), (2, 'INTERNAL')], default=1)),
                ('cancel_url', models.TextField(blank=True, null=True)),
                ('success_url', models.TextField(blank=True, null=True)),
                ('payment_platform_url', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='manual_subscription',
        ),
        migrations.AddField(
            model_name='transactions',
            name='blockchain_uuid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='object_type',
            field=models.CharField(choices=[('v', 'virtual'), ('c', 'crypto'), ('n', 'nft')], default='v', max_length=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseTracker',
        ),
        migrations.AddField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order'),
        ),
    ]
