# Generated by Django 2.2 on 2024-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_new_model'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION update_user_balance()
  RETURNS TRIGGER AS $$
DECLARE
    v_rec record;
BEGIN 
    select *
      into v_rec
      from users
     where id = NEW.user_id
       for update;
    
    IF NEW.object_type = 'v' THEN
        UPDATE users
        SET balance = balance + NEW.amount
        WHERE id = NEW.user_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
            """,
            """DROP FUNCTION update_user_balance();"""
        ),
        migrations.RunSQL(
            """
CREATE OR REPLACE TRIGGER trg_update_user_balance
AFTER INSERT ON transactions
FOR EACH ROW
WHEN (NEW.object_type = 'v')
EXECUTE PROCEDURE update_user_balance();
            """,
            """DROP TRIGGER trg_update_user_balance ON transactions;"""
        ),

    ]
