# Generated by Django 2.2 on 2024-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_update_feed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optafeeditem',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optafeeditem',
            name='event_id',
            field=models.CharField(max_length=50),
        ),
    ]
