# Generated by Django 2.2 on 2024-04-09 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_matchleaderboard_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(related_name='chat_rooms', to='core.CustomUser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.ChatRoom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomUser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.RunSQL("""
    CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $update_group_new$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
    $update_group_new$ LANGUAGE plpgsql;
    """),
    migrations.RunSQL("""
    CREATE OR REPLACE TRIGGER chat_room_updated_at
        BEFORE UPDATE ON chat_rooms FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    """),
        migrations.RunSQL("""
    INSERT INTO chat_rooms (id, name, description, created_at, updated_at) VALUES
        ('{}','laliga', 'LaLiga Chat Room', now(), now());"""
        .replace('{}', str(uuid.uuid4()))),
    ]
