# Generated by Django 2.2 on 2024-04-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_chatroommember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='competitionedition',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
