# Generated by Django 2.2 on 2024-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_chatroommember_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
