# Generated by Django 2.2 on 2024-05-07 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_match_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_id', models.CharField(max_length=128, null=True, unique=True)),
                ('name', models.TextField()),
                ('filter', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('related_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Competition')),
            ],
            options={
                'db_table': 'competition_config',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CompetitionConfig'),
        ),
    ]
