# Generated by Django 2.2 on 2024-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_sports_and_pwoerups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='normalized_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
