# Generated by Django 2.1.7 on 2020-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_normalized_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        # enable UUID generation in postgresql!
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'),
        # drop not null from updated_at and created_at will have now() as default
        migrations.RunSQL('''
            ALTER TABLE sports
                ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE sports
                ALTER COLUMN updated_at DROP NOT NULL;
        '''),
        # set cost as 0 by default in the powerups table
        migrations.RunSQL('''
            ALTER TABLE powerups
                ALTER COLUMN cost SET DEFAULT 0;
            ALTER TABLE powerups
                ALTER COLUMN enabled SET DEFAULT false;
        '''),
        # set ordering 10 (closest to highest as data would suggest) as default
        migrations.RunSQL('''
            ALTER TABLE powerup_actions
                ALTER COLUMN ordering SET DEFAULT 10;
        '''),
        # insert sport "Soccer" (futbol) and powerups
        migrations.RunSQL(
            '''
BEGIN;
DO $$
DECLARE
    sportID             UUID;
    typeGameEvent       INT := 1;
    typeGameSpecial     INT := 2; -- apply special rules
    maxPowerupID        INT;
    maxPowerupActionID  INT;
BEGIN
    SELECT uuid_generate_v4() INTO sportID;
    INSERT INTO sports(id, name, description) VALUES
        (sportID, 'Soccer', 'King of sports. Real name: Fútbol or Football');
    UPDATE actions SET sport_id = sportID; -- assume current actions are just soccer ones
    UPDATE powerups SET sport_id = sportID; -- assume current powerups are just soccer ones
    SELECT max(id) FROM powerups INTO maxPowerupID;
    PERFORM setval('powerups_id_seq', maxPowerupID);
    INSERT INTO powerups(sport_id, name, description, duration, multiplier, type) VALUES
    (sportID, 'Sharpshooter Pro', '2x points for positive shooting actions', 1200, 2, typeGameEvent), -- Shooting
    (sportID, 'Sharpshooter Elite', '2.5x points for positive shooting actions', 600, 2.5, typeGameEvent), -- Shooting
    (sportID, 'Sharpshooter Ultra', '3x points for positive shooting actions', 300, 3, typeGameEvent), -- Shooting
    (sportID, 'Playmaker Pro', '2x points for positive passing actions', 1200, 2, typeGameEvent), -- Passing
    (sportID, 'Playmaker Elite', '2.5x points for positive passing actions', 600, 2.5, typeGameEvent), -- Passing
    (sportID, 'Playmaker Ultra', '3x points for positive passing actions', 300, 3, typeGameEvent), -- Passing
    (sportID, 'Shield', 'Ignore negative points', 300, 1, typeGameSpecial), -- All events
    (sportID, 'Controller Pro', '2x points for positive dribbling actions', 1200, 2, typeGameEvent), -- Dribbling
    (sportID, 'Controller Elite', '2.5x points for positive dribbling actions', 600, 2.5, typeGameEvent), -- Dribbling
    (sportID, 'Controller Ultra', '3x points for positive dribbling actions', 300, 3, typeGameEvent), -- Dribbling
    (sportID, 'Guardian Pro', '2x points for positive goalkeeper actions', 1200, 2, typeGameEvent), -- goalkeeper
    (sportID, 'Guardian Elite', '2.5x points for positive goalkeeper actions', 600, 2.5, typeGameEvent), -- goalkeeper
    (sportID, 'Guardian Ultra', '3x points for positive goalkeeper actions', 300, 3, typeGameEvent), -- goalkeeper
    (sportID, 'Substitution', 'Swap out one of your players for another', 0, 0, typeGameSpecial), -- Special allow substitutions in game
    (sportID, 'Reverse', 'All negative points are treated as positive', 60, 1, typeGameSpecial); -- All events
    SELECT max(id) FROM powerup_actions INTO maxPowerupActionID;
    PERFORM setval('powerup_actions_id_seq', maxPowerupActionID);
    INSERT INTO powerup_actions(powerup_id, action_id)
    SELECT p.id, a.id FROM powerups p, actions a
        WHERE p.name ilike 'Sharpshooter%' and a.name ilike '%shot%' and score > 0;
    INSERT INTO powerup_actions(powerup_id, action_id)
    SELECT p.id, a.id FROM powerups p, actions a
            WHERE p.name ilike 'Playmaker%' and a.name ilike '%pass%' and score > 0;
    INSERT INTO powerup_actions(powerup_id, action_id)
    SELECT p.id, a.id FROM powerups p, actions a
            WHERE p.name ilike 'Controller%' and a.name ilike 'Dribble%' and score > 0;
    INSERT INTO powerup_actions(powerup_id, action_id)
    SELECT p.id, a.id FROM powerups p, actions a
            WHERE p.name ilike 'Guardian%' and a.description ilike 'keep%' and score > 0;
    UPDATE powerups SET enabled = TRUE;
END $$;
            ''',
            '''
            DELETE FROM powerup_actions WHERE powerup_id IN (select id FROM powerups WHERE id > 7);
            DELETE FROM powerups WHERE id > 7;
            setval('powerup_id_seq', 7);
            '''),
    ]
