# Generated by Django 2.2 on 2024-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_boosts_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreward',
            name='max_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='min_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchreward',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchreward',
            unique_together={('match', 'min_position', 'max_position')},
        ),
    ]
