# Generated by Django 2.2 on 2024-05-23 23:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20240521_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeedSimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.CharField(blank=True, max_length=50, null=True)),
                ('json_events', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Match')),
            ],
            options={
                'db_table': 'data_feed_sim',
            },
        ),
    ]
