# Generated by Django 2.2 on 2024-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_datafeedsimmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventThrottler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=32)),
                ('event_type', models.CharField(db_column='type', max_length=32)),
                ('data', models.TextField(blank=True)),
                ('processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_throttler',
            },
        ),
    ]
