# Generated by Django 2.2 on 2024-05-29 19:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_eventthrottler'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunSQL(
            '''UPDATE powerups
               SET conditions = '[{ "name": "shield"}]'
               WHERE name ilike 'Shield';
               UPDATE powerups
               SET conditions = '[{ "name": "substitution"}]'
               WHERE name ilike 'Substitution';
               UPDATE powerups
               SET conditions = '[{ "name": "reverse"}]'
               WHERE name ilike 'Reverse';'''
        )
    ]
