# Generated by Django 2.2 on 2024-05-29 19:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_powerup_conditions'),
    ]

    operations = [
        migrations.RunSQL(
            '''
INSERT INTO powerup_actions(powerup_id, action_id)
    SELECT p.id, a.id FROM powerups p, actions a
WHERE p.name ilike 'shield' or p.name ilike 'reverse';'''
        )
    ]
