# Generated by Django 2.2 on 2024-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_powerup_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
