# Generated by Django 2.2 on 2024-06-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sport'),
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sport'),
        ),
    ]
