# Generated by Django 2.2 on 2024-06-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_add_sport_relation_to_match_and_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sport'),
        ),
        migrations.AddField(
            model_name='competitionconfig',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sport'),
        ),
    ]
