# Generated by Django 2.2 on 2024-06-04 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_ads_sport_to_competition_and_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finished_games',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
