# Generated by Django 2.2 on 2024-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
