# Generated by Django 2.2 on 2024-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
