# Generated by Django 2.2 on 2024-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_chatroom_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='import_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
