# Generated by Django 2.2 on 2024-06-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_ppg_materialized_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optafeeditemversion',
            name='version',
            field=models.TextField(),
        ),
    ]
