# Generated by Django 2.2 on 2024-07-01 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20240621_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('apple_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('product_type', models.CharField(blank=True, choices=[('consumable', 'Consumable'), ('nonconsumable', 'Non-Consumable'), ('subscription', 'Subscription'), ('nft', 'NFT')], default='consumable', max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser')),
            ],
            options={
                'db_table': 'product_transactions',
            },
        ),
    ]
