# Generated by Django 2.2 on 2024-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_product_producttransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sequence_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
