# Generated by Django 2.2 on 2024-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransactions',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.DO_NOTHING, to='core.Transactions'),
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttransactions',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
