# Generated by Django 2.2 on 2024-07-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_product_transaction_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransactions',
            name='external_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
