# Generated by Django 2.2 on 2024-07-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_producttransactions_external_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='producttransactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CustomUser'),
        ),
    ]
