# Generated by Django 2.2 on 2024-07-10 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_product_name_to_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('team_id', models.UUIDField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('game_position', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('common_claiming', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_defence', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_distribution', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_dribbling', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_passing', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_shooting', models.FloatField(blank=True, default=0.0, null=True)),
                ('common_stopping', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_claiming', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_defence', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_distribution', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_dribbling', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_passing', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_shooting', models.FloatField(blank=True, default=0.0, null=True)),
                ('legendary_stopping', models.FloatField(blank=True, default=0.0, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rare_claiming', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_defence', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_distribution', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_dribbling', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_passing', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_shooting', models.FloatField(blank=True, default=0.0, null=True)),
                ('rare_stopping', models.FloatField(blank=True, default=0.0, null=True)),
                ('star_rating', models.FloatField(default=0.0)),
                ('ultra_rare_claiming', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_defence', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_distribution', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_dribbling', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_passing', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_shooting', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultra_rare_stopping', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_claiming', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_defence', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_distribution', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_dribbling', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_passing', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_shooting', models.FloatField(blank=True, default=0.0, null=True)),
                ('uncommon_stopping', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'db_table': 'nft_bucket',
            },
        ),
    ]
