# Generated by Django 2.2 on 2024-07-12 19:25

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_nftbucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='cardpacktype',
            name='tier1_guaranteed',
        ),
        migrations.RemoveField(
            model_name='cardpacktype',
            name='tier2_guaranteed',
        ),
        migrations.RemoveField(
            model_name='cardpacktype',
            name='tier3_guaranteed',
        ),
        migrations.RemoveField(
            model_name='cardpacktype',
            name='tier4_guaranteed',
        ),
        migrations.RemoveField(
            model_name='cardpacktype',
            name='tier5_guaranteed',
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='tier1',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='tier2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='tier3',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='tier4',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='tier5',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='common_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='common_metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='legendary_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='legendary_metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='rare_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='rare_metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='ultra_rare_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='ultra_rare_metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='uncommon_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='uncommon_metadata',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
