# Generated by Django 2.2 on 2024-07-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20240712_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedplayer',
            name='player_nft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.NftBucket'),
        ),
    ]
