# Generated by Django 2.2 on 2024-07-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_assignedplayer_player_nft'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='StoreProduct',
        ),
        migrations.RenameModel(
            old_name='ProductTransactions',
            new_name='StoreProductTransactions',
        ),
        migrations.AlterModelTable(
            name='storeproduct',
            table='store_products',
        ),
        migrations.AlterModelTable(
            name='storeproducttransactions',
            table='store_product_transactions',
        ),
    ]
