# Generated by Django 2.2 on 2024-07-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_rename_products_to_store_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='product_id',
            new_name='store_product_id',
        ),
    ]
