# Generated by Django 2.2 on 2024-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_rename_product_id_to_store_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedplayer',
            name='nft_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
