# Generated by Django 2.2 on 2024-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_assignedplayer_nft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcardpack',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedcardpack',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
