# Generated by Django 2.2 on 2024-07-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_remove_assignedplayer_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedplayer',
            name='user',
        ),
    ]
