# Generated by Django 2.2 on 2024-07-18 03:04

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_remove_assignedplayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcardpack',
            name='card_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
