# Generated by Django 2.2 on 2024-07-18 12:18

from django.db import migrations

def insert_division_data(apps, schema_editor):
    Division = apps.get_model('core', 'Division')
    divisions = [
        {'name': "Division 10", 'tier': 10, 'percentage': 0.08},
        {'name': "Division 9", 'tier': 9, 'percentage': 0.10},
        {'name': "Division 8", 'tier': 8, 'percentage': 0.15},
        {'name': "Division 7", 'tier': 7, 'percentage': 0.19},
        {'name': "Division 6", 'tier': 6, 'percentage': 0.15},
        {'name': "Division 5", 'tier': 5, 'percentage': 0.12},
        {'name': "Division 4", 'tier': 4, 'percentage': 0.09},
        {'name': "Division 3", 'tier': 3, 'percentage': 0.07},
        {'name': "Division 2", 'tier': 2, 'percentage': 0.04},
        {'name': "Division 1", 'tier': 1, 'percentage': 0.01},
    ]

    for division in divisions:
        Division.objects.create(name=division['name'], tier=division['tier'], percentage=division['percentage'])

def delete_division_data(apps, schema_editor):
    Division = apps.get_model('core', 'Division')
    Division.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20240719_1958'),
    ]

    operations = [
        migrations.RunPython(insert_division_data, reverse_code=delete_division_data),
    ]
