# Generated by Django 2.2 on 2024-07-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_auto_20240718_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepick',
            name='assigned_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_player', to='core.AssignedPlayer'),
        ),
    ]
