# Generated by Django 2.2 on 2024-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_gamepick_assigned_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedplayer',
            name='rarity',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
