# Generated by Django 2.2 on 2024-07-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_assignedplayer_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
