# Generated by Django 2.2 on 2024-07-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20240723_1804'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION insert_match_leaderboard_record() RETURNS TRIGGER
   LANGUAGE plpgsql
   AS $$
   DECLARE
        division_id UUID;
   BEGIN
        -- Fetch the most recent division_id for the user
        SELECT ud.division_id
        INTO division_id
        FROM user_divisions ud
        WHERE ud.user_id = NEW.user_id
        ORDER BY ud.created_at DESC
        LIMIT 1;
        
        -- Insert into match_leaderboard with division_id
        INSERT INTO match_leaderboard (match_id, game_id, user_id, score, position, division_id)
        VALUES (NEW.match_id, NEW.id, NEW.user_id, NULL, NULL, division_id);
        
        RETURN NEW;
    END;
    $$;
""",
            """DROP FUNCTION insert_match_leaderboard_record();"""
        ),

        migrations.RunSQL(
            """
DROP TRIGGER IF EXISTS trg_insert_match_leaderboard_record ON games;
            
CREATE TRIGGER trg_insert_match_leaderboard_record
AFTER INSERT ON games
FOR EACH ROW EXECUTE PROCEDURE insert_match_leaderboard_record();
            """,
            """DROP TRIGGER IF EXISTS trg_insert_match_leaderboard_record ON games;"""
        ),
    ]
