# Generated by Django 2.2 on 2024-07-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_add_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_id', models.CharField(max_length=128, null=True, unique=True)),
                ('name', models.TextField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_seasons',
            },
        ),
        migrations.RemoveField(
            model_name='season',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='season',
            name='start_at',
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.GameSeason'),
        ),
    ]
