# Generated by Django 2.2 on 2024-07-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20240725_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcardpack',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Transactions'),
        ),
    ]
