# Generated by Django 2.2 on 2024-07-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_assignedcardpack_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproducttransactions',
            name='origin_store',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
