# Generated by Django 2.2 on 2024-07-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_storeproducttransactions_origin_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpacktype',
            name='pack_limits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='common_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='legendary_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='rare_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='ultra_rare_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nftbucket',
            name='uncommon_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
