# Generated by Django 2.2 on 2024-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20240730_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpacktype',
            name='card_pack_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
