# Generated by Django 2.2 on 2024-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_cardpacktype_card_pack_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
