# Generated by Django 2.2 on 2024-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_add_season_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftbucket',
            name='players_group',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
