# Generated by Django 2.2 on 2024-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_nftbucket_players_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftbucket',
            name='opta_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
