# Generated by Django 2.2 on 2024-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_nftbucket_opta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='promotion_max_range',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='division',
            name='promotion_min_range',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='division',
            name='relegation_max_range',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='division',
            name='relegation_min_range',
            field=models.FloatField(default=0.2),
        ),
    ]
