# Generated by Django 2.2 on 2024-08-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20240802_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcardpack',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
