# Generated by Django 2.2 on 2024-08-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20240802_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcardpack',
            name='transaction',
        ),
        migrations.AddField(
            model_name='assignedcardpack',
            name='store_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.StoreProductTransactions'),
        ),
    ]
