# Generated by Django 2.2 on 2024-08-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20240802_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameweekhistory',
            name='week_average_rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergameweekhistory',
            name='weekly_matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
