# Generated by Django 2.2 on 2024-08-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20240806_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergameweekhistory',
            old_name='weekly_matches_played',
            new_name='week_matches_played',
        ),
    ]
