# Generated by Django 2.2 on 2024-08-13 01:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_appinbox_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinbox',
            name='user_id',
            field=models.UUIDField(blank=True, null=True, verbose_name=core.models.CustomUser),
        ),
    ]
