# Generated by Django 2.2 on 2024-08-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20240813_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinbox',
            name='user_id',
        ),
        migrations.AddField(
            model_name='appinbox',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appinbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CustomUser'),
        ),
    ]
