# Generated by Django 2.2 on 2024-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20240813_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='boost_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='nft_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='nft_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
