# Generated by Django 2.2 on 2024-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20240815_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcardpack',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
