# Generated by Django 2.2 on 2024-08-27 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_assignedcardpack_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.FloatField(default=0)),
                ('game_token', models.FloatField(default=0)),
                ('lapt_token', models.FloatField(default=0)),
                ('event_tickets', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
                ('signed_ball', models.IntegerField(default=0)),
                ('shirt', models.IntegerField(default=0)),
                ('signed_shirt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
        migrations.RemoveField(
            model_name='divisionreward',
            name='amount',
        ),
        migrations.AddField(
            model_name='matchreward',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='event',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='lapt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='shirts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='signed_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='signed_shirts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='object_type',
            field=models.CharField(choices=[('v', 'virtual'), ('c', 'crypto'), ('n', 'nft'), ('g', 'game'), ('l', 'lapt'), ('e', 'event_ticket'), ('m', 'merch'), ('b', 'ball'), ('a', 'signed_ball'), ('s', 'shirt'), ('h', 'signed_shirt')], default='v', max_length=1),
        ),
        migrations.AddField(
            model_name='divisionreward',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rewards'),
        ),
    ]
