# Generated by Django 2.2 on 2024-08-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20240827_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeekDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('promotion_count', models.FloatField()),
                ('relegation_count', models.FloatField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GameWeek')),
            ],
            options={
                'db_table': 'game_week_divisions',
            },
        ),
    ]
