# Generated by Django 2.2 on 2024-09-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20240903_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinbox',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appinbox',
            name='clamed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appinbox',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rewards'),
        ),
    ]
