# Generated by Django 2.2 on 2024-09-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_auto_20240903_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinbox',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appinbox',
            name='game_week_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GameWeek'),
        ),
        migrations.AddField(
            model_name='appinbox',
            name='match_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Match'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
