# Generated by Django 2.2 on 2024-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_auto_20240905_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='nft_category',
            field=models.TextField(blank=True, choices=[('distribution', 'distribution'), ('shooting', 'shooting'), ('passing', 'passing'), ('dribbling', 'dribbling'), ('defence', 'defence'), ('disciplinary', 'disciplinary'), ('stopping', 'stopping'), ('claiming', 'claiming')], null=True),
        ),
    ]
