# Generated by Django 2.2 on 2024-10-10 16:00

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_appinbox_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpacktype',
            name='rarities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='cardpacktype',
            name='star_ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
