# Generated by Django 2.2 on 2024-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_auto_20241010_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_bonus_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
