# Generated by Django 2.2 on 2024-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_customuser_referral_bonus_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreward',
            name='season_pack_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='season_pack_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreward',
            name='season_pack_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewards',
            name='season_pack_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewards',
            name='season_pack_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewards',
            name='season_pack_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='object_type',
            field=models.CharField(choices=[('v', 'virtual'), ('c', 'crypto'), ('n', 'nft'), ('g', 'game'), ('l', 'lapt'), ('e', 'event_ticket'), ('m', 'merch'), ('b', 'ball'), ('a', 'signed_ball'), ('s', 'shirt'), ('h', 'signed_shirt'), ('1', 'kickoff_pack_1'), ('2', 'kickoff_pack_2'), ('3', 'kickoff_pack_3'), ('4', 'season_pack_1'), ('5', 'season_pack_2'), ('6', 'season_pack_3')], default='v', max_length=1),
        ),
    ]
