# Generated by Django 2.2 on 2024-10-16 15:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_auto_20241014_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomUser')),
            ],
            options={
                'db_table': 'push_notifications',
            },
        ),
    ]
