steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mobile-api:$BRANCH_NAME.$COMMIT_SHA', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mobile-api:$BRANCH_NAME.$COMMIT_SHA']
- name: 'ubuntu'
  args: ['sed', '-i', 's/CLOUD_SQL_INSTANCE_ID/ufl-20:europe-west1:development/g', 'deploy/k8s/deployment.yaml']
- name: 'ubuntu'
  args: ['sed', '-i', 's/PROJECT_ID/$PROJECT_ID/g', 'deploy/k8s/deployment.yaml']
- name: 'ubuntu'
  args: ['sed', '-i', 's/BUILD_VERSION/$BRANCH_NAME.$COMMIT_SHA/g', 'deploy/k8s/deployment.yaml']
- name: 'ubuntu'
  args: ['sed', '-i', 's/NAMESPACE/staging/g', 'deploy/k8s/deployment.yaml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy/k8s']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=fanclash'